lag = 50.0
layers = 3
e2e_lag = 35.0
rng_seed = 0
log_file = "../../logs/logs.log"
body_size = 5436
base_port = 49152
time_unit = 1.0
start_time = 1575154800.901652
traces_file = "../../data/sample.json"
num_senders = 98
client_model = "ALL_SIMULATION"
num_providers = 3
nodes_per_layer = 3
loop_mix_entropy = true

[lambdas]
LOOP = 1.5
DROP = 1.5
DELAY = 1.0
PAYLOAD = 1.5
LOOP_MIX = 0.5
