lag              = 10.0
layers           = 2
rng_seed         = 0
log_file         = "../../logs/logs.log"
body_size        = 5436
time_unit        = 3.9395182525289467
start_time       = 1575154800.901652
traces_file      = "../../data/sample.json"
num_senders      = 14
client_model     = "ALL_SIMULATION"
num_providers    = 2
nodes_per_layer  = 2
loop_mix_entropy = true

[lambdas]
LOOP     = 7.879036505057893
DROP     = 7.879036505057893
LEGIT    = 7.879036505057893
DELAY    = 7.879036505057893
LOOP_MIX = 7.879036505057893